### ISSUE TITLE
FromIterator<F> for Unicycle<F> would be more ergonomic

### ISSUE THREAD

**Issue by dekellum** [udoprog/unicycle#2]
I tested one case, and I suspect it will be a common pattern for users to want to drop in `Unicycle` where `FuturesUnordered` was previously used.  The `Unicyle` would have been a drop in replacement if it implemented `FromIterator` like `FuturesUnordered` does, allowing it to be assembled via `std::iter::Iterator::collect`.

**Comment by udoprog** [comment]
Thanks for the report!
I've added naive implementations for `Collect` in master at the moment.

They could be improved to take [Iterator::size_hint] into account to pre-allocate the collections used, so I've opened #3 to track this.

[size_hint]: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.size_hint

**Comment by WyseNynja** [comment]
Can you share an example of using this? Thanks!

**Comment by udoprog** [comment]
Hey @WyseNynja

I added an example here: https://github.com/udoprog/unicycle/blob/master/src/lib.rs#L54

Does that help?

**Comment by WyseNynja** [comment]
Yes. Thank you!
