### ISSUE TITLE
PinSlab and Unordered leaks memory for non-Copy types

### ISSUE THREAD

**Issue by udoprog** [udoprog/unicycle#20]
I noticed that `PinVec` doesn't implement `Drop`, causing it to not de-allocate the elements held in it if `Unordered` is dropped.

This is fine in how its used for `InternalWaker`, but not when it's used as a backing store for `PinSlab` since it might contain futures that needs to be destructed.

Demonstrated in #19 

@eholk is this something you'd want to take a stab at?

**Comment by eholk** [comment]
Sure thing! I have a fix in #21.
