### ISSUE TITLE
Infinite wakeups

### ISSUE THREAD

**Issue by VShell** [udoprog/unicycle#5]
It appears that https://github.com/udoprog/unicycle/blob/807e146ebb86a8a20bc1d8e977e132b9efa8d59b/src/lib.rs#L751 is called if everything in the Unordered returns Poll::Pending - which results in an infinite wakeup loop. This is wasteful - the futures inside the FuturesUnordered should register themselves to be woken up, making this unnecessary?

**Comment by udoprog** [comment]
Hey!

Yeah, it looks like there's a check missing that was lost in refactoring. I believe if `wake_last` is empty _before_ it's drained, it should return `Poll::Pending`.

Thanks for the report, I'll fix it and make sure everything works as intended!
